### ISSUE TITLE
Jetson TX2 2대를 활용하여 Cluster구축

### ISSUE THREAD

**Issue by HexagonalED** [dcslab-edge/edge-profiler#5]
현재 JetsonTX2 한대에만 Spark-GPU가 구축되어있으며, 과제의 본 목표를 달성하기 위해서는 여러 노드에서 Spark-GPU를 설치, Streaming processing이 Cluster단위로 구현되어야합니다.

이를 위해서, 
- 남은 JetsonTX2에 Spark-GPU를 구축
- JetsonTX2 2대를 이어 Cluster를 구축

하는 필요가 있습니다.

현재 작업단계는 Spark-GPU를 빌드하고 있는 상태입니다.

**Comment by YoonsungNam** [comment]
edge-sched의 issue/1으로 통합함
